language: python
python:
  - "3.6"
  

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install codeclimate-test-reporter


script:
  - coverage run --source=tests/v1 -m pytest && coverage report
after_success:
  - coveralls
  -codeclimate-test-reporter

cache:
  - pip